name: Test Coverage

# on: [ push ]  # use this for non-plugins
# haraka-plugin-*, dummy event that never triggers
on: [ milestone ]

jobs:

  coverage:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install
      run: |
        npm install
        npm install --no-save nyc codecov

    - run: npx nyc --reporter=lcovonly npm test
      env:
        NODE_ENV: cov

    - name: Submit to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
